# ==========================================
# APPLICATION
# ==========================================
spring.application.name=identity-service
server.port=8085


# ==========================================
# DATABASE - MySQL
# ==========================================
spring.datasource.url=jdbc:mysql://localhost:3306/identity_db?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# ==========================================
# JPA / HIBERNATE
# ==========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false


# ==========================================
# CONNECTION POOL
# ==========================================
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=20000


# ==========================================
# CHARACTER ENCODING
# ==========================================
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true


# ==========================================
# JWT
# ==========================================
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000
